using System.Text;

namespace ReactiveUI.Generators
{
	/// <summary>
	/// Indented text for generated files, tab-indented to match the hand-written code beside it.
	/// </summary>
	internal sealed class SourceBuilder
	{
		private readonly StringBuilder _builder = new(1024);
		private int _depth;

		/// <summary>
		/// Starts a file with the header every generated file carries.
		/// </summary>
		/// <remarks>
		/// The <c>&lt;auto-generated&gt;</c> comment is what analyzers — Unity's included — key on to
		/// leave generated code alone.
		/// </remarks>
		public static SourceBuilder File(string source)
		{
			var builder = new SourceBuilder();

			builder.Line("// <auto-generated>");
			builder.Line($"// Generated by ReactiveUI.Generators from {source}. Edits here are lost on the next compile.");
			builder.Line("// </auto-generated>");
			builder.Line("#nullable enable");
			builder.Line();

			return builder;
		}

		public SourceBuilder Line(string text = "")
		{
			if (text.Length > 0)
				_builder.Append('\t', _depth).Append(text);

			_builder.Append('\n');

			return this;
		}

		public void Open(string header)
		{
			Line(header);
			Line("{");
			_depth++;
		}

		public void Close()
		{
			_depth--;
			Line("}");
		}

		/// <summary>
		/// Opens the namespace and every enclosing type of <paramref name="type"/>, then the type itself.
		/// </summary>
		/// <returns>How many blocks to <see cref="Close"/>.</returns>
		public int OpenType(DeclaredType type)
		{
			var opened = 0;

			if (type.Namespace.Length > 0)
			{
				Open($"namespace {type.Namespace}");
				opened++;
			}

			foreach (var scope in type.Containing)
			{
				Open($"partial {scope.Keyword} {scope.Name}");
				opened++;
			}

			Open($"partial {type.Self.Keyword} {type.Self.Name}");

			return opened + 1;
		}

		public void Close(int count)
		{
			for (var i = 0; i < count; i++)
				Close();
		}

		public override string ToString() => _builder.ToString();
	}
}
